name: Build and Publish

on:
  push:
    branches: [ ver/1.21.4 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'gradle'

      - name : Build with Gradle
        run: ./gradlew build

      - name : Publish package
        run: ./gradlew publishAllPublicationsToCaramelRepository
        env:
          DEPLOY_ID: ${{ secrets.DEPLOY_ID }}
          DEPLOY_PW: ${{ secrets.DEPLOY_PW }}
