name: Build Daydream-Helper

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name : Build with Gradle
        run: |
          chmod -R +x ./gradlew
          ./gradlew build --no-daemon
