name: Publish Daydream-Helper

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name : Build with Gradle
        run: |
          chmod -R +x ./gradlew
          ./gradlew build --no-daemon

      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToCaramelRepository
        env:
          DEPLOY_ID: ${{ secrets.DEPLOY_ID }}
          DEPLOY_PW: ${{ secrets.DEPLOY_PW }}
